"""Original, pose-specific drawing lessons for the four supported languages."""

LESSON_SLUGS = ("gesture", "balance", "seated")

LESSONS = {
    "ko": {
        "index_title": "사진 한 장을 더 깊게 보는 연습",
        "index_intro": "기본 가이드를 읽었다면, 실제 포즈를 보며 한 번에 한 가지 구조를 관찰해 보세요. 각 글에는 30초·1분·3분 과제와 복습 질문이 있습니다.",
        "related": "다음 연습법",
        "source_note": "예시 사진은 포즈토키를 위해 생성한 AI 이미지입니다. 인체 구조의 정답이 아니라 관찰 연습용 자료로 사용하세요.",
        "focus_title": "사진에서 먼저 찾을 세 지점",
        "timing_title": "같은 사진을 시간에 따라 다르게 그리기",
        "mistake_title": "흔한 실수와 수정 방법",
        "transfer_title": "다른 포즈에 적용하기",
        "review_title": "그린 뒤 확인할 질문",
        "practice_title": "지금 연습하기",
        "times": ("30초", "1분", "3분"),
        "gesture": {
            "title": "30초 동작선: 걷는 몸의 흐름을 한 줄로",
            "description": "걷는 인물 사진을 보며 동작선, 몸통의 방향, 앞발을 찾는 30초·1분·3분 크로키 연습.",
            "lead": "동작선은 척추를 베끼는 선이 아니라 포즈 전체가 어디로 향하는지 요약한 선입니다. PT014의 걷는 자세에서 얼굴이나 손가락을 잠시 잊고, 머리·가슴통·앞으로 나간 발의 관계를 먼저 읽어 보세요.",
            "primary": ("pose-07.jpg", "회색 스튜디오에서 한 발을 앞으로 내딛고 고개를 돌린 착의 인물", "PT014 포즈 · 걷기. 앞쪽 팔과 발이 서로 반대 방향으로 흔들리는 순간을 관찰합니다."),
            "markers": ((52, 15), (58, 33), (51, 75)),
            "focus": (
                "고개는 화면 왼쪽을 보지만 몸통의 큰 축은 아래로 이어집니다. 시선 방향을 몸 전체의 진행 방향과 혼동하지 마세요.",
                "가슴통과 골반을 옷의 외곽선 대신 단순한 두 덩어리로 생각합니다. 두 덩어리 사이의 흐름을 한 번에 그어 보세요.",
                "앞으로 나온 신발과 뒤에 남은 신발의 높이·겹침을 비교합니다. 동작선이 어느 발 쪽으로 내려오는지 결정하세요.",
            ),
            "timing": (
                "머리 위치를 작은 타원으로 표시하고, 몸통을 지나 앞발 쪽으로 내려오는 흐름 한 줄만 그립니다. 팔·얼굴은 생략합니다.",
                "가슴통과 골반을 두 덩어리로 추가하고, 팔과 다리를 긴 축 네 개로 연결합니다. 발의 앞뒤 관계만 정확히 남깁니다.",
                "첫 1분의 큰 구조를 유지한 채 무릎의 굽힘, 어깨의 회전, 발의 접지점을 확인합니다. 시간이 남을 때만 옷 주름을 더합니다.",
            ),
            "mistake": "고개가 왼쪽을 향한다는 이유로 몸통까지 왼쪽으로 눕히면 걷기의 균형이 사라집니다. 처음 그은 선을 지우기 전에 골반 아래의 지지 다리와 두 신발의 위치를 다시 비교하세요. 멋진 곡선보다 포즈가 서 있는 이유를 설명하는 선이 우선입니다.",
            "secondary": ("pose-17.jpg", "한쪽 발로 서서 다른 발을 잡고 반대쪽 팔을 뻗은 인물", "PT004 포즈 · 한 발 균형. 걷기보다 움직임은 작지만 팔과 다리가 서로 다른 방향으로 뻗습니다."),
            "transfer": "PT004 포즈에서는 뻗은 팔끝을 따라 긴 선을 그리기 쉽습니다. 그러나 몸의 무게는 바닥에 닿은 한 발이 받습니다. 먼저 머리에서 골반을 지나 지지 발까지 한 선을 그리고, 그다음 팔과 든 다리를 붙여 보세요. 두 포즈의 동작선이 왜 다른지 한 문장으로 적으면 관찰이 또렷해집니다.",
            "review": ("손과 얼굴을 가려도 걷는 방향이 읽히나요?", "가슴통과 골반을 연결한 선이 발의 배치와 어울리나요?", "움직이는 팔을 그리느라 지지 다리를 놓치지 않았나요?"),
            "practice": "연습실에서 30초·5장을 선택해 큰 흐름만 그린 뒤, 1분·5장으로 반복하세요. 한 장을 오래 고치기보다 두 번째 묶음에서 처음 놓친 지지 발을 찾는 것이 목표입니다.",
        },
        "balance": {
            "title": "1분 무게중심: 골반과 지지 발을 함께 보기",
            "description": "선 자세와 발판을 딛는 자세를 비교해 골반 기울기, 접지점, 무게중심을 읽는 크로키 연습.",
            "lead": "사람이 서 있는 그림이 어색할 때는 머리 크기보다 무게가 어디에 실렸는지 먼저 확인하세요. PT001 포즈의 어깨·골반·두 발을 비교하면 정지한 자세에도 미세한 기울기와 균형이 있다는 것을 볼 수 있습니다.",
            "primary": ("pose-01.jpg", "한 손을 허리에 얹고 두 다리의 위치를 달리해 서 있는 착의 인물", "PT001 포즈 · 선 자세. 어깨선과 골반선, 두 신발의 접지점을 따로 관찰합니다."),
            "markers": ((48, 28), (51, 45), (48, 88)),
            "focus": (
                "양어깨를 잇는 선을 먼저 가볍게 표시합니다. 머리가 기울었다고 어깨도 같은 각도라고 단정하지 마세요.",
                "허리 양쪽 높이와 바지의 허리선을 비교해 골반의 기울기를 찾습니다. 몸통을 직사각형 하나로 고정하지 않습니다.",
                "두 신발이 바닥과 만나는 지점을 찍습니다. 어느 다리가 몸통의 무게를 더 직접 받는지 사진의 축과 발 위치로 추론해 보세요.",
            ),
            "timing": (
                "머리·골반·두 발의 위치를 점 네 개로 놓고, 골반에서 지지 발로 내려가는 선을 그립니다. 외곽선을 닫지 않습니다.",
                "어깨선과 골반선을 추가한 뒤 두 선의 각도를 비교합니다. 지지 다리는 진하게, 보조 다리는 가볍게 그려 무게 차이를 표현합니다.",
                "가슴통의 부피, 무릎의 방향, 신발의 접지면을 더합니다. 마지막에는 머리 아래에서 바닥으로 내린 가상의 수직선이 어디를 지나는지 점검합니다.",
            ),
            "mistake": "두 다리를 같은 굵기와 길이의 기둥처럼 그리면 서 있는 자세가 뻣뻣해집니다. 한 다리는 무게를 받는 축, 다른 다리는 균형을 돕는 축으로 구별하세요. 사진만으로 압력의 크기를 확정할 수 없으므로, 발과 골반의 위치를 근거로 가설을 세우고 그림에서 설득력 있게 표현하는 것이 목적입니다.",
            "secondary": ("pose-19.jpg", "한 발을 낮은 발판에 올리고 균형을 잡는 착의 인물", "PT015 포즈 · 발판을 딛는 순간. 지지면의 높이가 달라지면 골반과 무릎의 방향도 바뀝니다."),
            "transfer": "PT015 포즈의 바닥과 발판 윗면을 서로 다른 높이의 두 수평선으로 표시하세요. 발판 위 발과 바닥의 발을 연결할 때 다리 길이를 억지로 맞추지 말고, 무릎이 어느 방향으로 접히는지 살핍니다. 웹툰 컷으로 옮길 때는 발판을 지워도 인물이 어떤 높이를 딛는지 읽히는지 확인해 보세요.",
            "review": ("발과 바닥의 접지점이 사진과 일치하나요?", "어깨선·골반선이 무심코 평행해지지 않았나요?", "몸통 아래로 내린 수직선이 지지면 근처에 도착하나요?"),
            "practice": "연습실에서 1분·5장을 고른 뒤 매 장마다 발 두 곳부터 표시하세요. 첫 묶음은 인체 비례보다 접지와 기울기만 평가하고, 다음 묶음에서 다리 길이를 다듬습니다.",
        },
        "seated": {
            "title": "3분 앉은 자세: 골반의 자리와 겹침 읽기",
            "description": "의자에 앉은 인물의 골반, 다리 겹침, 몸통 회전을 관찰하는 3분 크로키 연습.",
            "lead": "앉은 자세는 서 있는 인물을 허리에서 접은 모양이 아닙니다. 체중이 의자에 닿는 자리, 골반에서 뻗는 허벅지, 그 앞뒤로 겹치는 다리를 따로 봐야 합니다. PT049 포즈를 보며 접촉점부터 시작해 보세요.",
            "primary": ("pose-02.jpg", "검은 스툴에 앉아 다리를 겹치고 고개를 돌린 착의 인물", "PT049 포즈 · 스툴에 앉기. 골반과 좌면의 접촉, 겹친 다리, 바닥에 닿은 신발을 읽습니다."),
            "markers": ((50, 32), (51, 55), (64, 86)),
            "focus": (
                "몸통의 중심과 고개 방향은 다릅니다. 목이 돌아갔다고 가슴통 전체를 같은 방향으로 돌리지 마세요.",
                "골반이 스툴 좌면에 놓인 곳을 먼저 찾습니다. 이 접촉점이 흔들리면 다리를 아무리 정확히 그려도 앉은 느낌이 약해집니다.",
                "겹친 무릎과 바닥에 닿은 신발을 비교합니다. 사진에서 앞에 보이는 다리부터 선을 정리하고 가려진 부분은 그리지 않습니다.",
            ),
            "timing": (
                "스툴 좌면을 짧은 수평선으로 놓고 그 위에 골반 덩어리를 얹습니다. 머리와 발의 위치만 표시하고 멈춥니다.",
                "가슴통·골반·두 무릎을 연결합니다. 앞에 오는 다리의 윤곽을 먼저 그리고, 뒤 다리는 겹침이 드러나는 부분만 그립니다.",
                "몸통의 회전, 발과 바닥의 접점, 스툴 다리의 방향을 점검합니다. 손가락과 옷 주름은 구조가 읽힌 뒤 마지막에 더합니다.",
            ),
            "mistake": "겹친 다리를 두 개의 완전한 다리로 각각 그리면 무릎과 허벅지가 서로 뚫고 지나가는 것처럼 보입니다. 앞쪽 윤곽 하나를 먼저 확정하고, 뒤쪽 다리는 가려진 곳에서 선을 끊으세요. 보이지 않는 부분을 상상해 채우기보다 사진에서 확인되는 경계만 기록합니다.",
            "secondary": ("pose-21.jpg", "스툴에 앉아 한 팔을 대각선 위로 뻗는 착의 인물", "PT052 포즈 · 앉아 팔 뻗기. 좌면의 접촉은 유지되지만 몸통과 팔이 다른 방향으로 뻗습니다."),
            "transfer": "PT052 포즈를 볼 때는 먼저 스툴 좌면과 골반의 관계를 PT049 포즈와 같은 방식으로 잡으세요. 그다음 뻗은 팔의 긴 축과 몸통 기울기를 더합니다. 손끝에서 시작하면 앉은 몸의 안정감을 놓치기 쉽습니다. 웹툰 장면으로 바꿀 때도 의자를 지우기 전에 체중이 어느 면에 놓였는지 표시하세요.",
            "review": ("골반과 좌면이 실제로 맞닿아 보이나요?", "앞·뒤 다리의 겹침 순서가 사진과 같나요?", "팔과 얼굴의 세부를 빼도 앉은 방향이 읽히나요?"),
            "practice": "연습실에서 3분·5장을 선택하고 앉은 포즈가 나오면 첫 30초를 좌면과 골반에만 쓰세요. 다른 포즈가 나오면 ‘몸이 어디에 기대거나 닿는가’라는 같은 질문으로 관찰합니다.",
        },
    },
    "en": {
        "index_title": "Look more closely at one pose",
        "index_intro": "After the basic guide, study one structure at a time in real pose references. Each lesson includes 30-second, 1-minute, and 3-minute tasks plus review questions.",
        "related": "Continue learning",
        "source_note": "These reference photos were generated for PoseToki with AI. Use them to practice observation, not as anatomical ground truth.",
        "focus_title": "Three points to find before drawing",
        "timing_title": "Draw the same pose at three speeds",
        "mistake_title": "A common mistake—and a correction",
        "transfer_title": "Transfer the idea to another pose",
        "review_title": "Questions for your review",
        "practice_title": "Try it in the studio",
        "times": ("30 seconds", "1 minute", "3 minutes"),
        "gesture": {
            "title": "A 30-second gesture line for a walking figure",
            "description": "Use a walking pose to find the line of action, torso direction, and leading foot in 30-second, 1-minute, and 3-minute studies.",
            "lead": "A line of action is not a tracing of the spine. It summarizes where the whole pose is going. In pose PT014, set the face and fingers aside and first compare the head, rib cage, pelvis, and leading foot.",
            "primary": ("pose-07.jpg", "Clothed man stepping forward in a gray studio while turning his head", "Pose PT014 · Walking. Notice the opposing swing of the forward arm and leg."),
            "markers": ((52, 15), (58, 33), (51, 75)),
            "focus": (
                "The head looks toward the left of the frame, but the torso's main axis continues downward. Do not confuse gaze with the direction of the entire body.",
                "Think of the rib cage and pelvis as two simple masses rather than tracing the shirt and trousers. Connect their flow with one confident line.",
                "Compare the height and overlap of the front and rear shoes. Decide which foot the gesture line moves toward.",
            ),
            "timing": (
                "Place a small oval for the head, then draw one flow line through the torso toward the leading foot. Leave out the arms and face.",
                "Add two masses for rib cage and pelvis; connect the limbs with four long axes. Keep only the front–back relationship of the feet precise.",
                "Preserve the large structure. Check the bend of each knee, shoulder rotation, and where the shoes touch the floor. Add folds only if time remains.",
            ),
            "mistake": "If you lean the entire torso left simply because the head looks left, the walk loses its balance. Before erasing your first line, compare the supporting leg under the pelvis and the positions of both shoes. The useful line is the one that explains why the figure can stand, not merely the most elegant curve.",
            "secondary": ("pose-17.jpg", "Person balancing on one foot while holding the other foot and extending an arm", "Pose PT004 · One-foot balance. The limbs extend in different directions, even though the action is quieter."),
            "transfer": "It is tempting to follow the extended arm with one long gesture line. The weight, however, is carried by the foot on the floor. Draw a line from head through pelvis to that foot first; then attach the arm and lifted leg. Write one sentence explaining why the gesture line differs from the walking pose.",
            "review": ("Can you read the walk with the hands and face covered?", "Does the rib-cage-to-pelvis flow make sense with the feet?", "Did you lose the supporting leg while drawing the moving arm?"),
            "practice": "In the studio, choose 30 seconds and 5 poses to draw only the big flow. Repeat with 1 minute and 5 poses. Instead of polishing one sheet, use the second set to find the supporting foot you missed in the first.",
        },
        "balance": {
            "title": "One-minute balance: connect pelvis and supporting foot",
            "description": "Compare a standing pose and a step-up pose to study pelvic tilt, contact points, and visual weight.",
            "lead": "When a standing figure feels unstable, inspect where its weight appears to land before fixing the head size. Pose PT001 shows how a still stance can contain subtle tilts. Compare the shoulders, pelvis, and both feet before outlining the clothes.",
            "primary": ("pose-01.jpg", "Clothed person standing with one hand on the hip and the legs in different positions", "Pose PT001 · Standing. Examine the shoulder line, pelvic line, and two shoe contacts separately."),
            "markers": ((48, 28), (51, 45), (48, 88)),
            "focus": (
                "Lightly mark the line joining the shoulders. A tilted head does not automatically mean the shoulders have the same angle.",
                "Compare the height of the two sides of the waist and the trouser waistband to estimate pelvic tilt. Avoid locking the torso into one rectangle.",
                "Mark where both shoes meet the floor. Use their placement and the torso axis to infer which leg appears to carry more of the weight.",
            ),
            "timing": (
                "Place four points: head, pelvis, and two feet. Draw from pelvis toward the apparent supporting foot; leave the outline open.",
                "Add shoulder and pelvic lines and compare their angles. Give the supporting leg a firmer line and the balancing leg a lighter one.",
                "Add rib-cage volume, knee direction, and shoe contact surfaces. Finally, imagine a vertical line dropped from the upper body and see where it reaches the floor.",
            ),
            "mistake": "Two legs drawn as equally thick, equally loaded pillars make a stance rigid. Treat one as the likely weight-bearing axis and the other as a balancing axis. A photo cannot reveal exact pressure, so this is an observation-based hypothesis to make visually convincing, not a measured biomechanical claim.",
            "secondary": ("pose-19.jpg", "Clothed person placing one foot on a low block while balancing", "Pose PT015 · Stepping onto a block. Different support heights change the pelvis and knees."),
            "transfer": "Mark the floor and top of the block as two horizontal lines at different heights. Do not force the legs to look equal when connecting the block foot to the floor foot; observe which way each knee folds. For a comic panel, hide the block briefly and ask whether the figure still reads as stepping to a higher level.",
            "review": ("Do the foot-to-floor contacts match the reference?", "Did you make shoulder and pelvic lines parallel by habit?", "Does a vertical line from the upper body reach a plausible support area?"),
            "practice": "Choose 1 minute and 5 poses in the studio. Mark both foot contacts first on every sheet. Review the first set only for support and tilt; refine leg lengths in a second set.",
        },
        "seated": {
            "title": "Three-minute seated poses: contact and overlap",
            "description": "Read the pelvic contact, overlapping legs, and torso turn in a seated figure during a practical three-minute drawing study.",
            "lead": "A seated figure is not simply a standing figure folded at the waist. Find where weight meets the seat, where the thighs leave the pelvis, and which leg passes in front. Pose PT049 gives you a clear contact point to start from.",
            "primary": ("pose-02.jpg", "Clothed person seated on a black stool with crossed legs and head turned", "Pose PT049 · On a stool. Read pelvis-to-seat contact, overlapping legs, and the shoe touching the floor."),
            "markers": ((50, 32), (51, 55), (64, 86)),
            "focus": (
                "The torso's orientation differs from the head's gaze. A turned neck does not mean the entire rib cage turns by the same amount.",
                "Find where the pelvis rests on the stool seat. If that contact drifts, even accurately drawn legs will not feel seated.",
                "Compare the overlapping knees and the shoe on the floor. Resolve the nearer leg's visible edge first; leave hidden parts undrawn.",
            ),
            "timing": (
                "Place the stool seat as a short horizontal line and a simple pelvic mass on top. Mark only head and foot positions before stopping.",
                "Connect rib cage, pelvis, and both knees. Draw the nearer leg's outline first and only the visible portions of the rear leg.",
                "Check torso rotation, foot-to-floor contact, and stool-leg direction. Add fingers and clothing folds only after the structure reads clearly.",
            ),
            "mistake": "Drawing both overlapping legs as complete shapes can make the thighs seem to pass through one another. Establish one front contour, then break the rear line wherever it is hidden. Record the boundaries visible in the photo instead of inventing every concealed edge.",
            "secondary": ("pose-21.jpg", "Person seated on a stool and reaching one arm diagonally upward", "Pose PT052 · Seated reach. The seat contact stays, while torso and arm extend in new directions."),
            "transfer": "Start pose PT052 with the stool seat and pelvis, exactly as you did for pose PT049. Only then add the long reaching arm and torso tilt. Beginning at the fingertips makes it easy to lose the body's seated stability. In a comic panel, mark the weight-bearing surface before removing the chair from your sketch.",
            "review": ("Does the pelvis visibly meet the seat?", "Does the front-to-back order of the legs match the photo?", "Can you read the seated direction without arm and face details?"),
            "practice": "Set the studio to 3 minutes and 5 poses. Whenever a seated pose appears, spend the first 30 seconds only on seat and pelvis. On other poses, ask the same question: where does this body touch or lean on something?",
        },
    },
    "ja": {
        "index_title": "一枚のポーズを、もう一歩深く見る",
        "index_intro": "基本のガイドを読んだら、実際のポーズで一度に一つの構造を観察しましょう。各レッスンに30秒・1分・3分の課題と見直しの問いがあります。",
        "related": "次に読むレッスン",
        "source_note": "参考写真は PoseToki のために AI で生成した画像です。人体構造の正解としてではなく、観察練習の題材として使ってください。",
        "focus_title": "描く前に見つけたい三つの点",
        "timing_title": "同じ写真を三つの時間で描く",
        "mistake_title": "よくある間違いと直し方",
        "transfer_title": "別のポーズで試す",
        "review_title": "描いた後の確認",
        "practice_title": "練習室で試す",
        "times": ("30秒", "1分", "3分"),
        "gesture": {
            "title": "30秒の動勢線：歩く身体を一本の線で捉える",
            "description": "歩く人物の写真から動勢線、胴体の向き、前に出た足を探す30秒・1分・3分のクロッキー練習。",
            "lead": "動勢線は背骨の写しではなく、ポーズ全体の流れを要約する線です。PT014の歩くポーズでは顔や指をいったん忘れ、頭・胸郭・骨盤・前に出た足の関係から見てみましょう。",
            "primary": ("pose-07.jpg", "灰色のスタジオで一歩を踏み出し、顔を横に向けた服を着た男性", "PT014・歩くポーズ。腕と脚が逆方向に振れる瞬間を観察します。"),
            "markers": ((52, 15), (58, 33), (51, 75)),
            "focus": (
                "顔は画面の左を向いていても、胴体の大きな軸は下へ続きます。視線と身体全体の進む方向を混同しないでください。",
                "胸郭と骨盤を服の輪郭ではなく、二つの単純な塊として見ます。その間の流れを一本の線でつないでみましょう。",
                "前後の靴の高さと重なりを比べます。動勢線をどちらの足へ下ろすか決めてください。",
            ),
            "timing": (
                "頭を小さな楕円で置き、胴体から前の足へ向かう流れを一本だけ描きます。腕と顔は省略します。",
                "胸郭と骨盤を二つの塊で足し、腕と脚を四本の長い軸でつなぎます。足の前後関係だけは明確に残します。",
                "最初の大きな構造を保ち、膝の曲がり、肩の回転、靴の接地点を確かめます。服のしわは時間が残ったときだけ加えます。",
            ),
            "mistake": "顔が左を向くからと胴体まで左へ倒すと、歩く姿勢の均衡が崩れます。最初の線を消す前に、骨盤の下にある支持脚と両方の靴の位置を見比べましょう。きれいな曲線より、その姿勢が立てる理由を示す線が大切です。",
            "secondary": ("pose-17.jpg", "片足で立ち、もう一方の足を持ちながら腕を横に伸ばす人物", "PT004・片足のバランス。動きは小さくても手足は異なる方向へ伸びます。"),
            "transfer": "伸ばした腕に沿って長い線を引きたくなりますが、体重を受けるのは床につく片足です。まず頭から骨盤を通って支持脚へ一本の線を引き、その後で腕と上げた脚を付けます。歩くポーズと動勢線が違う理由を一文にしてみましょう。",
            "review": ("手と顔を隠しても歩く方向が読めますか。", "胸郭と骨盤をつなぐ流れは足の配置と合いますか。", "動く腕に気を取られて支持脚を忘れていませんか。"),
            "practice": "練習室で30秒・5ポーズを選び、大きな流れだけを描きます。次に1分・5ポーズで繰り返しましょう。一枚を磨くより、二回目に見落とした支持脚を見つけることが目標です。",
        },
        "balance": {
            "title": "1分で重心を見る：骨盤と支持脚をつなぐ",
            "description": "立ち姿と段差に足を置く姿を比べ、骨盤の傾き、接地点、重さの見え方を学ぶクロッキー練習。",
            "lead": "立ち姿が不安定に見えたら、頭の大きさを直す前に重さがどこへ落ちるかを見ます。PT001の写真で肩・骨盤・両足を比べると、静かなポーズにも小さな傾きと均衡があると分かります。",
            "primary": ("pose-01.jpg", "片手を腰に当て、左右の脚の位置を変えて立つ服を着た人物", "PT001・立ち姿。肩の線、骨盤の線、二つの靴の接地点を分けて見ます。"),
            "markers": ((48, 28), (51, 45), (48, 88)),
            "focus": (
                "両肩を結ぶ線を薄く引きます。頭が傾いていても、肩まで同じ角度とは限りません。",
                "左右の腰の高さとズボンの腰線を比べ、骨盤の傾きを探します。胴体を一つの四角形に固定しないでください。",
                "両方の靴が床に触れる場所を印します。胴体の軸と足の位置から、どちらの脚が重さを多く受けているように見えるか考えます。",
            ),
            "timing": (
                "頭・骨盤・両足の四点を置き、骨盤から支持脚へ下りる線を引きます。外形は閉じません。",
                "肩線と骨盤線を加え、角度を比べます。支持脚をやや強く、バランスを取る脚を軽く描き分けます。",
                "胸郭の厚み、膝の向き、靴と床の接触面を足します。最後に上半身から下ろした仮の垂線が床のどこへ届くか確認します。",
            ),
            "mistake": "両脚を同じ太さ・同じ重さの柱として描くと、立ち姿が硬くなります。一方を主な支持軸、もう一方をバランスを補う軸として区別しましょう。写真だけで足裏の圧力は測れません。足と骨盤の位置を根拠に、納得できる見え方を作るための仮説です。",
            "secondary": ("pose-19.jpg", "低い台に片足を置き、バランスを取る服を着た人物", "PT015・台に足を置く瞬間。支持面の高さが変わると骨盤と膝の向きも変わります。"),
            "transfer": "床と台の上面を高さの異なる二本の水平線で示します。台の足と床の足をつなぐとき、脚を無理に同じ長さにせず、膝がどちらへ曲がるか見ましょう。漫画のコマでは台を一度隠し、それでも人物が高い場所へ踏み出すように読めるか試してください。",
            "review": ("足と床の接地点は写真と合っていますか。", "肩線と骨盤線を無意識に平行にしていませんか。", "上半身から下ろした垂線は支持面の近くに届きますか。"),
            "practice": "練習室で1分・5ポーズを選び、毎回まず両足の接地点を印します。最初の一組は支持と傾きだけを見直し、次の一組で脚の長さを整えましょう。",
        },
        "seated": {
            "title": "3分の座りポーズ：骨盤の接触と脚の重なり",
            "description": "椅子に座る人物の骨盤、脚の前後関係、胴体の回転を観察する3分クロッキー。",
            "lead": "座り姿は立ち姿を腰で折っただけの形ではありません。体重が座面に乗る場所、骨盤から伸びる太もも、前後に重なる脚を別々に見ます。PT049の写真では接触点から始めましょう。",
            "primary": ("pose-02.jpg", "黒いスツールに座り、脚を重ねて顔を横へ向けた服を着た人物", "PT049・スツールに座る。骨盤と座面の接触、脚の重なり、床につく靴を見ます。"),
            "markers": ((50, 32), (51, 55), (64, 86)),
            "focus": (
                "胴体の向きと視線の向きは違います。首が回っても胸郭全体が同じだけ回るとは限りません。",
                "骨盤がスツールの座面に乗る場所を探します。ここがずれると脚が正しくても座っている感じが弱くなります。",
                "重なった膝と床につく靴を比べます。手前の脚の見える輪郭から決め、隠れた部分は描きません。",
            ),
            "timing": (
                "座面を短い水平線で置き、その上に骨盤の塊を乗せます。頭と足の位置だけを印して止めます。",
                "胸郭・骨盤・両膝をつなぎます。手前の脚の輪郭を先に描き、後ろの脚は見える部分だけ描きます。",
                "胴体の回転、足と床の接点、スツールの脚の向きを確認します。指や服のしわは構造が読めた後に加えます。",
            ),
            "mistake": "重なる両脚をそれぞれ完全な形で描くと、太ももが互いを突き抜けて見えます。前の輪郭を一つ決め、後ろの脚の線は隠れる所で切りましょう。見えない境界を想像で埋めず、写真で確かめられる線だけを残します。",
            "secondary": ("pose-21.jpg", "スツールに座って片腕を斜め上へ伸ばす人物", "PT052・座って手を伸ばす。座面との接触は保ったまま、胴体と腕が別方向へ伸びます。"),
            "transfer": "PT052もPT049と同じく、まず座面と骨盤の関係から始めます。その後で伸ばした腕の長い軸と胴体の傾きを足しましょう。指先から描き始めると座る身体の安定感を見失いがちです。漫画の場面に変えるときも、椅子を省く前に体重が乗る面を印してください。",
            "review": ("骨盤と座面が接して見えますか。", "前後の脚の重なり方は写真と同じですか。", "腕と顔の細部がなくても座る向きが読めますか。"),
            "practice": "練習室で3分・5ポーズを選び、座り姿が出たら最初の30秒を座面と骨盤だけに使います。別のポーズでは「身体はどこに触れ、何に支えられるか」と同じ問いを使ってください。",
        },
    },
    "zh-TW": {
        "index_title": "更仔細地看懂一張姿勢照片",
        "index_intro": "讀完基礎指南後，試著在實際姿勢中一次觀察一種結構。每篇練習都有 30 秒、1 分鐘、3 分鐘的任務，以及畫後檢查問題。",
        "related": "接著練習",
        "source_note": "這些參考照片是為 PoseToki 製作的 AI 圖像。請用來練習觀察，不要當作人體解剖的標準答案。",
        "focus_title": "下筆前先找出三個位置",
        "timing_title": "同一張照片，分三種時間畫",
        "mistake_title": "常見錯誤與修正方法",
        "transfer_title": "換一個姿勢再試一次",
        "review_title": "畫完後問自己",
        "practice_title": "到練習室試試",
        "times": ("30 秒", "1 分鐘", "3 分鐘"),
        "gesture": {
            "title": "30 秒動勢線：用一條線抓住走路的方向",
            "description": "用走路姿勢練習動勢線、軀幹方向與前腳位置，分別進行 30 秒、1 分鐘和 3 分鐘速寫。",
            "lead": "動勢線不是照著脊椎描線，而是概括整個姿勢的流向。看 PT014走路姿勢時，先放下臉和手指，觀察頭部、胸廓、骨盆與前腳的關係。",
            "primary": ("pose-07.jpg", "灰色攝影棚中踏出一步並轉頭的著衣男性", "PT014姿勢・走路。觀察手臂與腳在相反方向擺動的瞬間。"),
            "markers": ((52, 15), (58, 33), (51, 75)),
            "focus": (
                "頭望向畫面左側，但軀幹的主要軸線仍往下延伸。別把視線方向當成整個身體的前進方向。",
                "把胸廓與骨盆想成兩個簡單的體塊，不必沿著衣服邊緣描。試著用一條連續的線接起它們的流向。",
                "比較前後兩隻鞋的高度與遮擋關係，再決定動勢線要往哪隻腳落下。",
            ),
            "timing": (
                "用小橢圓標出頭，畫一條通過軀幹、走向前腳的線。手臂和臉先省略。",
                "加入胸廓、骨盆兩個體塊，以四條長軸接上四肢。先把腳的前後關係交代清楚。",
                "保留前一分鐘的大結構，檢查膝蓋彎曲、肩膀旋轉和鞋子的接地點。還有時間才加衣褶。",
            ),
            "mistake": "因為臉朝左就把整個軀幹也畫得向左倒，走路的平衡便會消失。擦掉第一條線之前，先比較骨盆下方的支撐腿與兩隻鞋的位置。能說明姿勢如何站穩的線，比漂亮的曲線更有用。",
            "secondary": ("pose-17.jpg", "單腳站立、手抓另一隻腳並向側面伸出手臂的人物", "PT004姿勢・單腳平衡。動作較小，但手腳朝不同方向伸展。"),
            "transfer": "很容易沿著伸出的手臂畫一條長線，但重量由落地的那隻腳承擔。先從頭經骨盆畫到支撐腳，再補上手臂與抬起的腿。試著用一句話說出它與走路姿勢的動勢線有何不同。",
            "review": ("遮住手和臉，還看得出走路方向嗎？", "胸廓到骨盆的流向與兩腳位置相符嗎？", "畫擺動的手臂時，有沒有漏掉支撐腿？"),
            "practice": "在練習室選 30 秒、5 個姿勢，只畫大方向；接著選 1 分鐘、5 個姿勢再畫一次。目標不是反覆修同一張，而是在第二輪找到第一輪漏看的支撐腳。",
        },
        "balance": {
            "title": "1 分鐘看重心：連起骨盆與支撐腳",
            "description": "比較站姿與踩上台階的姿勢，觀察骨盆傾斜、接地點與視覺重量。",
            "lead": "站著的人物看起來不穩時，先別急著改頭部大小，而要問重量落在哪裡。比較 PT001照片中的肩膀、骨盆與雙腳，就會發現靜止姿勢也有細微的傾斜與平衡。",
            "primary": ("pose-01.jpg", "一手叉腰、兩腿位置不同的著衣站姿人物", "PT001姿勢・站立。分開觀察肩線、骨盆線與兩隻鞋的接地點。"),
            "markers": ((48, 28), (51, 45), (48, 88)),
            "focus": (
                "先輕輕標出連接雙肩的線。頭有傾斜，不代表肩膀一定是同樣的角度。",
                "比較腰部兩側的高度與褲頭方向，找出骨盆傾斜。不要把整個軀幹固定成一個長方形。",
                "標出兩隻鞋碰到地面的地方，根據軀幹軸線與腳的位置，推測哪條腿看起來承受更多重量。",
            ),
            "timing": (
                "放下頭、骨盆與雙腳四個點，再畫出骨盆通往支撐腳的線，不急著封閉外輪廓。",
                "加入肩線與骨盆線並比較角度。用較肯定的線畫支撐腿，較輕的線畫協助平衡的腿。",
                "補上胸廓厚度、膝蓋方向與鞋底接觸面。最後想像一條從上半身落下的垂線，看它落在地面哪裡。",
            ),
            "mistake": "把兩條腿畫成一樣粗、一樣承重的柱子，站姿就會僵硬。試著區分主要支撐軸與協助平衡的軸。單靠照片無法測出腳底的實際壓力；這是根據腳和骨盆位置提出的觀察假設，目的是讓畫面更可信。",
            "secondary": ("pose-19.jpg", "一隻腳踏在矮台上並維持平衡的著衣人物", "PT015姿勢・踩上矮台。支撐面的高度不同，骨盆與膝蓋方向也會改變。"),
            "transfer": "先把地板與台面畫成不同高度的兩條水平線。連接台上的腳與地上的腳時，不要勉強兩條腿看起來一樣長，先觀察膝蓋往哪裡彎。畫漫畫分鏡時，可暫時遮住台階，看看人物是否仍像正要踏上較高處。",
            "review": ("腳與地面的接觸點和照片一致嗎？", "肩線與骨盆線是否被習慣性地畫成平行？", "從上半身落下的垂線是否接近合理的支撐面？"),
            "practice": "在練習室選 1 分鐘、5 個姿勢，每張先標雙腳接地點。第一輪只檢查支撐與傾斜，第二輪再修整腿的長度。",
        },
        "seated": {
            "title": "3 分鐘坐姿：看懂骨盆接觸與雙腿遮擋",
            "description": "用三分鐘觀察坐姿人物的骨盆接觸、腿部前後關係及軀幹轉向。",
            "lead": "坐姿不是把站著的人從腰部折起來。要分別看重量落在椅面的地方、大腿從骨盆伸出的方向，以及兩腿誰在前、誰在後。看 PT049照片時，從接觸點開始。",
            "primary": ("pose-02.jpg", "坐在黑色高腳凳上、雙腿交疊並轉頭的著衣人物", "PT049姿勢・坐在高腳凳上。觀察骨盆與椅面的接觸、腿部交疊與落地的鞋。"),
            "markers": ((50, 32), (51, 55), (64, 86)),
            "focus": (
                "軀幹方向與視線方向不同。脖子轉過去，不表示胸廓也轉了相同角度。",
                "找出骨盆壓在凳面上的位置。接觸點若漂移，腿部畫得再準也不容易有坐穩的感覺。",
                "比較交疊的膝蓋與碰到地面的鞋。先確定前方那條腿看得見的輪廓，遮住的部分不用畫。",
            ),
            "timing": (
                "用短水平線標出凳面，在上面放一個骨盆體塊。只再標頭和腳的位置就停筆。",
                "連起胸廓、骨盆與雙膝。先畫前方腿的輪廓，後方的腿只畫看得見的部分。",
                "檢查軀幹轉向、鞋與地面的接點、高腳凳椅腳的方向。結構清楚後才加手指與衣褶。",
            ),
            "mistake": "若把交疊的兩腿各自畫成完整形狀，大腿會看起來互相穿過。先確定前方的一條輪廓，後方腿的線在被擋住的地方中斷。不要憑想像補滿看不見的邊界，只記錄照片中能確認的部分。",
            "secondary": ("pose-21.jpg", "坐在高腳凳上並將一隻手臂斜向上伸的人物", "PT052姿勢・坐著伸手。骨盆仍接觸椅面，但軀幹與手臂朝新的方向延伸。"),
            "transfer": "觀察 PT052時，像 PT049一樣先找椅面與骨盆，再加入伸出的手臂長軸與軀幹傾斜。若從指尖開始，容易漏掉坐姿的穩定感。改編成漫畫場景時，省略椅子之前先標出重量壓在哪個面上。",
            "review": ("骨盆看起來真的貼在椅面上嗎？", "兩腿前後遮擋的順序與照片相同嗎？", "不畫手臂和臉部細節，仍看得出坐姿方向嗎？"),
            "practice": "在練習室選 3 分鐘、5 個姿勢。出現坐姿時，前 30 秒只畫椅面與骨盆。遇到別的姿勢，也問自己同一件事：身體接觸或倚靠的是哪裡？",
        },
    },
}
